#!/usr/bin/env python3
"""Generate Zed editor themes based on master palettes from paletteinspiration.com."""

import json
import os

THEMES_DIR = os.path.expanduser("~/.config/zed/themes")

def hex_to_rgb(hex_color):
    h = hex_color.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

def rgb_to_hex(r, g, b):
    return f"#{int(r):02x}{int(g):02x}{int(b):02x}"

def lighten(hex_color, amount=0.2):
    r, g, b = hex_to_rgb(hex_color)
    r = min(255, r + (255 - r) * amount)
    g = min(255, g + (255 - g) * amount)
    b = min(255, b + (255 - b) * amount)
    return rgb_to_hex(r, g, b)

def darken(hex_color, amount=0.3):
    r, g, b = hex_to_rgb(hex_color)
    r = max(0, r * (1 - amount))
    g = max(0, g * (1 - amount))
    b = max(0, b * (1 - amount))
    return rgb_to_hex(r, g, b)

def with_alpha(hex_color, alpha):
    """Return hex color with alpha (0-255)."""
    return f"{hex_color}{int(alpha):02x}"

# Artist theme definitions
ARTISTS = [
    {
        "id": "monet",
        "name": "Monet",
        "theme_name": "Monet — Veiled Parchment",
        "subtitle": "Inspired by Claude Monet's luminous impressionism",
        "appearance": "dark",
        "bg": "#1c1c1f",
        "editor_bg": "#1f1f22",
        "surface": "#26262a",
        "elevated": "#2e2e33",
        "text": "#c8cac9",
        "text_muted": "#8e9090",
        "border": "#3a3a40",
        "border_focused": "#5b657f",
        "comment": "#747776",
        "keyword": "#99adcb",
        "string": "#b4995a",
        "function": "#7b9eb5",
        "type": "#9db07a",
        "variable": "#b4aa96",
        "number": "#c9a86a",
        "constant": "#ae8e6d",
        "operator": "#999fac",
        "punctuation": "#8e9090",
        "boolean": "#7baabd",
        "property": "#8d9a6d",
        "tag": "#7b9eb5",
        "attribute": "#b4995a",
        "error": "#c47070",
        "warning": "#c4a050",
        "success": "#7aaa7a",
        "info": "#7a9abc",
        "accent": "#5b657f",
        "cursor": "#99adcb",
        "selection": "#5b657f44",
        "ansi_black": "#2d2b2e",
        "ansi_red": "#c47070",
        "ansi_green": "#7aaa7a",
        "ansi_yellow": "#c4a050",
        "ansi_blue": "#7a9abc",
        "ansi_magenta": "#a080a8",
        "ansi_cyan": "#70a0a0",
        "ansi_white": "#c8cac9",
    },
    {
        "id": "van-gogh",
        "name": "Van Gogh",
        "theme_name": "Van Gogh — Veiled Tawny",
        "subtitle": "Inspired by Vincent van Gogh's bold post-impressionism",
        "appearance": "dark",
        "bg": "#161210",
        "editor_bg": "#1a1612",
        "surface": "#221e18",
        "elevated": "#2c2820",
        "text": "#cdc4a2",
        "text_muted": "#8e8870",
        "border": "#383020",
        "border_focused": "#6e8bc8",
        "comment": "#666347",
        "keyword": "#6e8bc8",
        "string": "#d2b45e",
        "function": "#7b9f6b",
        "type": "#c88a4a",
        "variable": "#a8aea9",
        "number": "#b9773a",
        "constant": "#d4c070",
        "operator": "#a07d4a",
        "punctuation": "#8e8870",
        "boolean": "#8bb07b",
        "property": "#c4a060",
        "tag": "#6e8bc8",
        "attribute": "#d2b45e",
        "error": "#c85050",
        "warning": "#d2a040",
        "success": "#7ba070",
        "info": "#6e8bc8",
        "accent": "#6e8bc8",
        "cursor": "#d2b45e",
        "selection": "#6e8bc844",
        "ansi_black": "#231b18",
        "ansi_red": "#c85050",
        "ansi_green": "#7b9f6b",
        "ansi_yellow": "#d2b45e",
        "ansi_blue": "#6e8bc8",
        "ansi_magenta": "#a87898",
        "ansi_cyan": "#6aa098",
        "ansi_white": "#cdc4a2",
    },
    {
        "id": "matisse",
        "name": "Matisse",
        "theme_name": "Matisse — Muted Tawny",
        "subtitle": "Inspired by Henri Matisse's bold fauvism",
        "appearance": "dark",
        "bg": "#222020",
        "editor_bg": "#272424",
        "surface": "#302c2c",
        "elevated": "#3a3535",
        "text": "#dbd3c2",
        "text_muted": "#908d88",
        "border": "#423c3c",
        "border_focused": "#6b82b8",
        "comment": "#6e716e",
        "keyword": "#6b82b8",
        "string": "#caa354",
        "function": "#c85a44",
        "type": "#c3a883",
        "variable": "#aaa7a2",
        "number": "#d0a850",
        "constant": "#b8c090",
        "operator": "#857b59",
        "punctuation": "#908d88",
        "boolean": "#7b94c4",
        "property": "#d0a070",
        "tag": "#c85a44",
        "attribute": "#caa354",
        "error": "#c85a44",
        "warning": "#caa354",
        "success": "#7aa870",
        "info": "#6b82b8",
        "accent": "#c85a44",
        "cursor": "#c85a44",
        "selection": "#6b82b844",
        "ansi_black": "#332e2e",
        "ansi_red": "#c85a44",
        "ansi_green": "#7aa870",
        "ansi_yellow": "#caa354",
        "ansi_blue": "#6b82b8",
        "ansi_magenta": "#b070a0",
        "ansi_cyan": "#6aa0a0",
        "ansi_white": "#dbd3c2",
    },
    {
        "id": "renoir",
        "name": "Renoir",
        "theme_name": "Renoir — Muted Caramel",
        "subtitle": "Inspired by Pierre-Auguste Renoir's sun-dappled warmth",
        "appearance": "dark",
        "bg": "#1a1614",
        "editor_bg": "#1e1a17",
        "surface": "#272220",
        "elevated": "#312b28",
        "text": "#ccbfac",
        "text_muted": "#8e8474",
        "border": "#3a3430",
        "border_focused": "#c8935a",
        "comment": "#7a7268",
        "keyword": "#c8935a",
        "string": "#cfaf7b",
        "function": "#c86840",
        "type": "#b17f45",
        "variable": "#ae9473",
        "number": "#d4a065",
        "constant": "#cc9e6e",
        "operator": "#958174",
        "punctuation": "#8e8474",
        "boolean": "#b89060",
        "property": "#bb8555",
        "tag": "#c86840",
        "attribute": "#cfaf7b",
        "error": "#c86040",
        "warning": "#d4a040",
        "success": "#7a9a68",
        "info": "#8098b0",
        "accent": "#c86840",
        "cursor": "#cfaf7b",
        "selection": "#c8935a44",
        "ansi_black": "#302423",
        "ansi_red": "#c86040",
        "ansi_green": "#7a9a68",
        "ansi_yellow": "#d4a040",
        "ansi_blue": "#8098b0",
        "ansi_magenta": "#b07888",
        "ansi_cyan": "#6a9898",
        "ansi_white": "#ccbfac",
    },
    {
        "id": "pissarro",
        "name": "Pissarro",
        "theme_name": "Pissarro — Veiled Tawny",
        "subtitle": "Inspired by Camille Pissarro's naturalistic impressionism",
        "appearance": "dark",
        "bg": "#181614",
        "editor_bg": "#1c1a17",
        "surface": "#252220",
        "elevated": "#2e2a28",
        "text": "#cac2b7",
        "text_muted": "#8a8278",
        "border": "#383430",
        "border_focused": "#b0a058",
        "comment": "#6c676a",
        "keyword": "#b0a058",
        "string": "#baa074",
        "function": "#a07840",
        "type": "#7b8540",
        "variable": "#98897c",
        "number": "#c4a860",
        "constant": "#b89860",
        "operator": "#5c4f40",
        "punctuation": "#8a8278",
        "boolean": "#9ea060",
        "property": "#a89468",
        "tag": "#a07840",
        "attribute": "#baa074",
        "error": "#c07050",
        "warning": "#c4a040",
        "success": "#7a9868",
        "info": "#7a90a8",
        "accent": "#b0a058",
        "cursor": "#b0a058",
        "selection": "#b0a05844",
        "ansi_black": "#29211f",
        "ansi_red": "#c07050",
        "ansi_green": "#7a9868",
        "ansi_yellow": "#c4a040",
        "ansi_blue": "#7a90a8",
        "ansi_magenta": "#a07898",
        "ansi_cyan": "#6a9890",
        "ansi_white": "#cac2b7",
    },
    {
        "id": "roerich",
        "name": "Roerich",
        "theme_name": "Roerich — Dimmed Parchment",
        "subtitle": "Inspired by Nicholas Roerich's mystical mountain visions",
        "appearance": "dark",
        "bg": "#262224",
        "editor_bg": "#2b2728",
        "surface": "#353132",
        "elevated": "#3e3a3b",
        "text": "#e1dedc",
        "text_muted": "#a09d9b",
        "border": "#484344",
        "border_focused": "#5b72b8",
        "comment": "#8b8170",
        "keyword": "#9db4d4",
        "string": "#d19a47",
        "function": "#5b72b8",
        "type": "#d6bd92",
        "variable": "#bcb7b6",
        "number": "#c8a05a",
        "constant": "#a8bdd6",
        "operator": "#8b8170",
        "punctuation": "#a09d9b",
        "boolean": "#8db0d0",
        "property": "#b89a60",
        "tag": "#5b72b8",
        "attribute": "#d19a47",
        "error": "#c86050",
        "warning": "#d19a47",
        "success": "#6aaa78",
        "info": "#5b72b8",
        "accent": "#5b72b8",
        "cursor": "#9db4d4",
        "selection": "#5b72b844",
        "ansi_black": "#3f3738",
        "ansi_red": "#c86050",
        "ansi_green": "#6aaa78",
        "ansi_yellow": "#d19a47",
        "ansi_blue": "#5b72b8",
        "ansi_magenta": "#a070b0",
        "ansi_cyan": "#5a9aaa",
        "ansi_white": "#e1dedc",
    },
    {
        "id": "sargent",
        "name": "Sargent",
        "theme_name": "Sargent — Shadowed Tawny",
        "subtitle": "Inspired by John Singer Sargent's dramatic portraiture",
        "appearance": "dark",
        "bg": "#110e12",
        "editor_bg": "#161318",
        "surface": "#1e1b22",
        "elevated": "#28252e",
        "text": "#d9d0ca",
        "text_muted": "#8e8a86",
        "border": "#342e38",
        "border_focused": "#8088a8",
        "comment": "#6a6260",
        "keyword": "#8088a8",
        "string": "#c8a16d",
        "function": "#b07248",
        "type": "#d7c6a5",
        "variable": "#988f93",
        "number": "#c4a070",
        "constant": "#a8a0b0",
        "operator": "#917a5f",
        "punctuation": "#8e8a86",
        "boolean": "#7888a8",
        "property": "#c0a878",
        "tag": "#8088a8",
        "attribute": "#c8a16d",
        "error": "#c06050",
        "warning": "#c8a040",
        "success": "#70a070",
        "info": "#7888a8",
        "accent": "#8088a8",
        "cursor": "#d9d0ca",
        "selection": "#8088a844",
        "ansi_black": "#191417",
        "ansi_red": "#c06050",
        "ansi_green": "#70a070",
        "ansi_yellow": "#c8a040",
        "ansi_blue": "#7888a8",
        "ansi_magenta": "#a078a0",
        "ansi_cyan": "#6898a0",
        "ansi_white": "#d9d0ca",
    },
    {
        "id": "aivazovsky",
        "name": "Aivazovsky",
        "theme_name": "Aivazovsky — Veiled Parchment",
        "subtitle": "Inspired by Ivan Aivazovsky's dramatic seascapes",
        "appearance": "dark",
        "bg": "#171716",
        "editor_bg": "#1c1c1a",
        "surface": "#242422",
        "elevated": "#2e2e2c",
        "text": "#dbd7cc",
        "text_muted": "#9a968d",
        "border": "#38382e",
        "border_focused": "#709ab0",
        "comment": "#6a6658",
        "keyword": "#90a0b8",
        "string": "#ddc58c",
        "function": "#709ab0",
        "type": "#b4814c",
        "variable": "#aeb1ab",
        "number": "#c8b070",
        "constant": "#88a8b8",
        "operator": "#857d6a",
        "punctuation": "#9a968d",
        "boolean": "#80a0a8",
        "property": "#c0a870",
        "tag": "#709ab0",
        "attribute": "#ddc58c",
        "error": "#c06050",
        "warning": "#d0a840",
        "success": "#6aa878",
        "info": "#709ab0",
        "accent": "#709ab0",
        "cursor": "#90a0b8",
        "selection": "#709ab044",
        "ansi_black": "#272725",
        "ansi_red": "#c06050",
        "ansi_green": "#6aa878",
        "ansi_yellow": "#d0a840",
        "ansi_blue": "#709ab0",
        "ansi_magenta": "#a078a8",
        "ansi_cyan": "#5aa0a0",
        "ansi_white": "#dbd7cc",
    },
    {
        "id": "cezanne",
        "name": "Cézanne",
        "theme_name": "Cézanne — Penumbral Tawny",
        "subtitle": "Inspired by Paul Cézanne's structured post-impressionism",
        "appearance": "dark",
        "bg": "#141214",
        "editor_bg": "#191618",
        "surface": "#222020",
        "elevated": "#2c2928",
        "text": "#cec2a8",
        "text_muted": "#8e8878",
        "border": "#363230",
        "border_focused": "#a8bca0",
        "comment": "#70706d",
        "keyword": "#a8bca0",
        "string": "#c2a25c",
        "function": "#c07848",
        "type": "#8b9060",
        "variable": "#a8a6a0",
        "number": "#c4a060",
        "constant": "#b0a880",
        "operator": "#9f7e57",
        "punctuation": "#8e8878",
        "boolean": "#98b090",
        "property": "#b89860",
        "tag": "#c07848",
        "attribute": "#c2a25c",
        "error": "#c06048",
        "warning": "#c4a040",
        "success": "#78a870",
        "info": "#7898a8",
        "accent": "#c07848",
        "cursor": "#cec2a8",
        "selection": "#a8bca044",
        "ansi_black": "#1e191a",
        "ansi_red": "#c06048",
        "ansi_green": "#78a870",
        "ansi_yellow": "#c4a040",
        "ansi_blue": "#7898a8",
        "ansi_magenta": "#a878a0",
        "ansi_cyan": "#6a9898",
        "ansi_white": "#cec2a8",
    },
    {
        "id": "degas",
        "name": "Degas",
        "theme_name": "Degas — Shadowed Gamboge",
        "subtitle": "Inspired by Edgar Degas's intimate ballet scenes",
        "appearance": "dark",
        "bg": "#181414",
        "editor_bg": "#1e1919",
        "surface": "#272222",
        "elevated": "#312b2b",
        "text": "#cec2ae",
        "text_muted": "#8e8678",
        "border": "#3a3434",
        "border_focused": "#c0985a",
        "comment": "#6b6669",
        "keyword": "#c0985a",
        "string": "#ceb16a",
        "function": "#a8684a",
        "type": "#b28045",
        "variable": "#aa9a83",
        "number": "#d0b070",
        "constant": "#c8b080",
        "operator": "#977553",
        "punctuation": "#8e8678",
        "boolean": "#b89858",
        "property": "#b89060",
        "tag": "#a8684a",
        "attribute": "#ceb16a",
        "error": "#c06050",
        "warning": "#d0a040",
        "success": "#78a068",
        "info": "#7890a8",
        "accent": "#c0985a",
        "cursor": "#ceb16a",
        "selection": "#c0985a44",
        "ansi_black": "#281b1b",
        "ansi_red": "#c06050",
        "ansi_green": "#78a068",
        "ansi_yellow": "#d0a040",
        "ansi_blue": "#7890a8",
        "ansi_magenta": "#a87898",
        "ansi_cyan": "#689898",
        "ansi_white": "#cec2ae",
    },
    # --- 10 new artists below ---
    {
        "id": "da-vinci",
        "name": "Leonardo da Vinci",
        "theme_name": "Da Vinci — Veiled Tawny",
        "subtitle": "Inspired by Leonardo da Vinci's Renaissance mastery",
        "appearance": "dark",
        "bg": "#141210",
        "editor_bg": "#1a1714",
        "surface": "#23201c",
        "elevated": "#2d2a24",
        "text": "#e8dab2",
        "text_muted": "#9a8e78",
        "border": "#382e24",
        "border_focused": "#608497",
        "comment": "#776858",
        "keyword": "#608497",
        "string": "#c99f5e",
        "function": "#7a9aae",
        "type": "#c5b79c",
        "variable": "#9a7950",
        "number": "#d4b070",
        "constant": "#b8a87a",
        "operator": "#776858",
        "punctuation": "#9a8e78",
        "boolean": "#70a0b0",
        "property": "#c5a570",
        "tag": "#608497",
        "attribute": "#c99f5e",
        "error": "#c06050",
        "warning": "#c9a040",
        "success": "#6a9a68",
        "info": "#608497",
        "accent": "#608497",
        "cursor": "#e8dab2",
        "selection": "#60849744",
        "ansi_black": "#191613",
        "ansi_red": "#c06050",
        "ansi_green": "#6a9a68",
        "ansi_yellow": "#c9a040",
        "ansi_blue": "#608497",
        "ansi_magenta": "#9878a0",
        "ansi_cyan": "#5a9898",
        "ansi_white": "#e8dab2",
    },
    {
        "id": "rembrandt",
        "name": "Rembrandt",
        "theme_name": "Rembrandt — Shadowed Bister",
        "subtitle": "Inspired by Rembrandt's dramatic chiaroscuro",
        "appearance": "dark",
        "bg": "#0f0c0b",
        "editor_bg": "#141110",
        "surface": "#1e1a18",
        "elevated": "#282420",
        "text": "#d2c4ab",
        "text_muted": "#866c5c",
        "border": "#332a22",
        "border_focused": "#ddb571",
        "comment": "#554b4a",
        "keyword": "#ddb571",
        "string": "#af7943",
        "function": "#c8a060",
        "type": "#d2c4ab",
        "variable": "#866c5c",
        "number": "#d4b870",
        "constant": "#c8a870",
        "operator": "#765633",
        "punctuation": "#866c5c",
        "boolean": "#c8a060",
        "property": "#af7943",
        "tag": "#ddb571",
        "attribute": "#af7943",
        "error": "#b84030",
        "warning": "#ddb050",
        "success": "#6a8a58",
        "info": "#7890a8",
        "accent": "#ddb571",
        "cursor": "#ddb571",
        "selection": "#ddb57144",
        "ansi_black": "#161111",
        "ansi_red": "#b84030",
        "ansi_green": "#6a8a58",
        "ansi_yellow": "#ddb050",
        "ansi_blue": "#7890a8",
        "ansi_magenta": "#a07088",
        "ansi_cyan": "#5a9090",
        "ansi_white": "#d2c4ab",
    },
    {
        "id": "picasso",
        "name": "Picasso",
        "theme_name": "Picasso — Muted Tawny",
        "subtitle": "Inspired by Pablo Picasso's revolutionary cubism",
        "appearance": "dark",
        "bg": "#181515",
        "editor_bg": "#1e1b1a",
        "surface": "#282524",
        "elevated": "#33302e",
        "text": "#d7c7ab",
        "text_muted": "#8f8d80",
        "border": "#3e3a38",
        "border_focused": "#495f7a",
        "comment": "#4f4b42",
        "keyword": "#6a80a0",
        "string": "#c9a15e",
        "function": "#b75c2c",
        "type": "#b78056",
        "variable": "#8f8d80",
        "number": "#d0a860",
        "constant": "#c4a878",
        "operator": "#866c4b",
        "punctuation": "#8f8d80",
        "boolean": "#6a88a8",
        "property": "#c09050",
        "tag": "#b75c2c",
        "attribute": "#c9a15e",
        "error": "#b75c2c",
        "warning": "#c9a040",
        "success": "#6a9868",
        "info": "#6a80a0",
        "accent": "#495f7a",
        "cursor": "#d7c7ab",
        "selection": "#495f7a44",
        "ansi_black": "#231d1d",
        "ansi_red": "#b75c2c",
        "ansi_green": "#6a9868",
        "ansi_yellow": "#c9a040",
        "ansi_blue": "#6a80a0",
        "ansi_magenta": "#a07088",
        "ansi_cyan": "#5a9898",
        "ansi_white": "#d7c7ab",
    },
    {
        "id": "vermeer",
        "name": "Vermeer",
        "theme_name": "Vermeer — Shadowed Bister",
        "subtitle": "Inspired by Johannes Vermeer's luminous interiors",
        "appearance": "dark",
        "bg": "#131216",
        "editor_bg": "#181618",
        "surface": "#222020",
        "elevated": "#2c2a2a",
        "text": "#d3cec2",
        "text_muted": "#898071",
        "border": "#352e28",
        "border_focused": "#4b5a74",
        "comment": "#694f33",
        "keyword": "#7080a0",
        "string": "#bca06a",
        "function": "#a1abbd",
        "type": "#d3cec2",
        "variable": "#898071",
        "number": "#c8a870",
        "constant": "#b4a880",
        "operator": "#694f33",
        "punctuation": "#898071",
        "boolean": "#8098b8",
        "property": "#bca06a",
        "tag": "#ab3a1f",
        "attribute": "#bca06a",
        "error": "#ab3a1f",
        "warning": "#c8a040",
        "success": "#6a9868",
        "info": "#7080a0",
        "accent": "#4b5a74",
        "cursor": "#a1abbd",
        "selection": "#4b5a7444",
        "ansi_black": "#1c1a1e",
        "ansi_red": "#c05040",
        "ansi_green": "#6a9868",
        "ansi_yellow": "#c8a040",
        "ansi_blue": "#7080a0",
        "ansi_magenta": "#9870a0",
        "ansi_cyan": "#5a9898",
        "ansi_white": "#d3cec2",
    },
    {
        "id": "turner",
        "name": "Turner",
        "theme_name": "Turner — Veiled Tawny",
        "subtitle": "Inspired by J.M.W. Turner's atmospheric luminism",
        "appearance": "dark",
        "bg": "#1a1810",
        "editor_bg": "#201e16",
        "surface": "#29261e",
        "elevated": "#332e26",
        "text": "#d0c9b7",
        "text_muted": "#827662",
        "border": "#3c3428",
        "border_focused": "#cfb16e",
        "comment": "#5c616c",
        "keyword": "#8898b0",
        "string": "#cfb16e",
        "function": "#b2763e",
        "type": "#b4a080",
        "variable": "#827662",
        "number": "#d0b070",
        "constant": "#c8a870",
        "operator": "#886740",
        "punctuation": "#827662",
        "boolean": "#90a0b0",
        "property": "#c4a868",
        "tag": "#b2763e",
        "attribute": "#cfb16e",
        "error": "#c06048",
        "warning": "#d0a840",
        "success": "#6a9868",
        "info": "#7090a8",
        "accent": "#cfb16e",
        "cursor": "#cfb16e",
        "selection": "#cfb16e44",
        "ansi_black": "#332721",
        "ansi_red": "#c06048",
        "ansi_green": "#6a9868",
        "ansi_yellow": "#d0a840",
        "ansi_blue": "#7090a8",
        "ansi_magenta": "#a07898",
        "ansi_cyan": "#5a9898",
        "ansi_white": "#d0c9b7",
    },
    {
        "id": "klimt",
        "name": "Klimt",
        "theme_name": "Klimt — Muted Tawny",
        "subtitle": "Inspired by Gustav Klimt's gilded art nouveau",
        "appearance": "dark",
        "bg": "#1e1a18",
        "editor_bg": "#242020",
        "surface": "#2e2928",
        "elevated": "#383332",
        "text": "#ccbfa8",
        "text_muted": "#848887",
        "border": "#403830",
        "border_focused": "#dcb35c",
        "comment": "#5b5246",
        "keyword": "#dcb35c",
        "string": "#a59165",
        "function": "#e9523a",
        "type": "#a9644c",
        "variable": "#78765b",
        "number": "#d8b860",
        "constant": "#ccbfa8",
        "operator": "#5b5246",
        "punctuation": "#848887",
        "boolean": "#dcb35c",
        "property": "#a59165",
        "tag": "#e9523a",
        "attribute": "#dcb35c",
        "error": "#e9523a",
        "warning": "#dcb35c",
        "success": "#6a9a68",
        "info": "#8898b0",
        "accent": "#dcb35c",
        "cursor": "#dcb35c",
        "selection": "#dcb35c44",
        "ansi_black": "#352927",
        "ansi_red": "#e9523a",
        "ansi_green": "#6a9a68",
        "ansi_yellow": "#dcb35c",
        "ansi_blue": "#8898b0",
        "ansi_magenta": "#a070a0",
        "ansi_cyan": "#5aa0a0",
        "ansi_white": "#ccbfa8",
    },
    {
        "id": "kandinsky",
        "name": "Kandinsky",
        "theme_name": "Kandinsky — Muted Tawny",
        "subtitle": "Inspired by Wassily Kandinsky's abstract expressionism",
        "appearance": "dark",
        "bg": "#181616",
        "editor_bg": "#1e1c1b",
        "surface": "#282524",
        "elevated": "#33302e",
        "text": "#dad2bb",
        "text_muted": "#90938e",
        "border": "#3a3634",
        "border_focused": "#444583",
        "comment": "#515767",
        "keyword": "#6068a8",
        "string": "#dcc158",
        "function": "#b04937",
        "type": "#c3803c",
        "variable": "#968559",
        "number": "#d8c060",
        "constant": "#c8a858",
        "operator": "#6a4538",
        "punctuation": "#90938e",
        "boolean": "#6878b0",
        "property": "#c3803c",
        "tag": "#b04937",
        "attribute": "#dcc158",
        "error": "#b04937",
        "warning": "#dcc158",
        "success": "#6a9a68",
        "info": "#6068a8",
        "accent": "#444583",
        "cursor": "#dcc158",
        "selection": "#44458344",
        "ansi_black": "#2b2523",
        "ansi_red": "#b04937",
        "ansi_green": "#6a9a68",
        "ansi_yellow": "#dcc158",
        "ansi_blue": "#6068a8",
        "ansi_magenta": "#a060a0",
        "ansi_cyan": "#5a9898",
        "ansi_white": "#dad2bb",
    },
    {
        "id": "gauguin",
        "name": "Gauguin",
        "theme_name": "Gauguin — Shadowed Caramel",
        "subtitle": "Inspired by Paul Gauguin's vivid post-impressionism",
        "appearance": "dark",
        "bg": "#181414",
        "editor_bg": "#1e1a18",
        "surface": "#282420",
        "elevated": "#322e2a",
        "text": "#cbc2ac",
        "text_muted": "#968c7f",
        "border": "#3c3428",
        "border_focused": "#b2592b",
        "comment": "#5a5157",
        "keyword": "#c49a47",
        "string": "#8a7e46",
        "function": "#b2592b",
        "type": "#8e5b34",
        "variable": "#968c7f",
        "number": "#c8a850",
        "constant": "#b8a060",
        "operator": "#645936",
        "punctuation": "#968c7f",
        "boolean": "#c4a050",
        "property": "#8e7040",
        "tag": "#b2592b",
        "attribute": "#c49a47",
        "error": "#b2592b",
        "warning": "#c49a47",
        "success": "#6a9868",
        "info": "#7090a8",
        "accent": "#b2592b",
        "cursor": "#c49a47",
        "selection": "#b2592b44",
        "ansi_black": "#2a1e1f",
        "ansi_red": "#b2592b",
        "ansi_green": "#6a9868",
        "ansi_yellow": "#c49a47",
        "ansi_blue": "#7090a8",
        "ansi_magenta": "#a07090",
        "ansi_cyan": "#5a9890",
        "ansi_white": "#cbc2ac",
    },
    {
        "id": "caravaggio",
        "name": "Caravaggio",
        "theme_name": "Caravaggio — Nocturnal Bister",
        "subtitle": "Inspired by Caravaggio's intense tenebrism",
        "appearance": "dark",
        "bg": "#0d0b0a",
        "editor_bg": "#121010",
        "surface": "#1c1918",
        "elevated": "#262220",
        "text": "#d5c6ae",
        "text_muted": "#8b8384",
        "border": "#302820",
        "border_focused": "#d8b76f",
        "comment": "#3f3025",
        "keyword": "#d8b76f",
        "string": "#a1794e",
        "function": "#c89850",
        "type": "#d5c6ae",
        "variable": "#8b8384",
        "number": "#d4b870",
        "constant": "#c4a860",
        "operator": "#67513b",
        "punctuation": "#8b8384",
        "boolean": "#c8a860",
        "property": "#a1794e",
        "tag": "#994b29",
        "attribute": "#d8b76f",
        "error": "#994b29",
        "warning": "#d8b050",
        "success": "#6a8a58",
        "info": "#7888a0",
        "accent": "#d8b76f",
        "cursor": "#d8b76f",
        "selection": "#d8b76f44",
        "ansi_black": "#13100f",
        "ansi_red": "#b04030",
        "ansi_green": "#6a8a58",
        "ansi_yellow": "#d8b050",
        "ansi_blue": "#7888a0",
        "ansi_magenta": "#987088",
        "ansi_cyan": "#5a8888",
        "ansi_white": "#d5c6ae",
    },
    {
        "id": "raphael",
        "name": "Raphael",
        "theme_name": "Raphael — Shadowed Tawny",
        "subtitle": "Inspired by Raphael's harmonious Renaissance ideals",
        "appearance": "dark",
        "bg": "#131110",
        "editor_bg": "#191614",
        "surface": "#23201e",
        "elevated": "#2e2a28",
        "text": "#e1d8c9",
        "text_muted": "#b49d87",
        "border": "#382e28",
        "border_focused": "#686c7e",
        "comment": "#7f604d",
        "keyword": "#8090b0",
        "string": "#e2c291",
        "function": "#a24635",
        "type": "#c18b63",
        "variable": "#b49d87",
        "number": "#d8c090",
        "constant": "#c8b090",
        "operator": "#7f604d",
        "punctuation": "#b49d87",
        "boolean": "#8098b8",
        "property": "#c18b63",
        "tag": "#a24635",
        "attribute": "#e2c291",
        "error": "#a24635",
        "warning": "#d0a840",
        "success": "#6a9868",
        "info": "#8090b0",
        "accent": "#686c7e",
        "cursor": "#a4adb8",
        "selection": "#686c7e44",
        "ansi_black": "#1d1817",
        "ansi_red": "#b04838",
        "ansi_green": "#6a9868",
        "ansi_yellow": "#d0a840",
        "ansi_blue": "#8090b0",
        "ansi_magenta": "#a070a0",
        "ansi_cyan": "#5a9898",
        "ansi_white": "#e1d8c9",
    },
    {
        "id": "munch",
        "name": "Munch",
        "theme_name": "Munch — Muted Tawny",
        "subtitle": "Inspired by Edvard Munch's raw expressionism",
        "appearance": "dark",
        "bg": "#161414",
        "editor_bg": "#1c1a1a",
        "surface": "#262424",
        "elevated": "#302e2e",
        "text": "#d2cab9",
        "text_muted": "#9a9994",
        "border": "#3a3636",
        "border_focused": "#b5572d",
        "comment": "#6f644e",
        "keyword": "#8890a8",
        "string": "#cf9f55",
        "function": "#b5572d",
        "type": "#b59773",
        "variable": "#9a9994",
        "number": "#d0a858",
        "constant": "#c8a870",
        "operator": "#7d4932",
        "punctuation": "#9a9994",
        "boolean": "#8898a8",
        "property": "#b59060",
        "tag": "#b5572d",
        "attribute": "#cf9f55",
        "error": "#b5572d",
        "warning": "#cf9f55",
        "success": "#6a9868",
        "info": "#79798c",
        "accent": "#b5572d",
        "cursor": "#d2cab9",
        "selection": "#b5572d44",
        "ansi_black": "#241f20",
        "ansi_red": "#b5572d",
        "ansi_green": "#6a9868",
        "ansi_yellow": "#cf9f55",
        "ansi_blue": "#79798c",
        "ansi_magenta": "#a07090",
        "ansi_cyan": "#5a9898",
        "ansi_white": "#d2cab9",
    },
    {
        "id": "velazquez",
        "name": "Velázquez",
        "theme_name": "Velázquez — Nocturnal Bister",
        "subtitle": "Inspired by Diego Velázquez's masterful realism",
        "appearance": "dark",
        "bg": "#0e0c0b",
        "editor_bg": "#141210",
        "surface": "#1e1a18",
        "elevated": "#282420",
        "text": "#d5c9b0",
        "text_muted": "#848378",
        "border": "#302820",
        "border_focused": "#be8f52",
        "comment": "#453b2a",
        "keyword": "#9098b0",
        "string": "#be8f52",
        "function": "#b64b32",
        "type": "#bba281",
        "variable": "#848378",
        "number": "#c8a060",
        "constant": "#c0a070",
        "operator": "#7f5d36",
        "punctuation": "#848378",
        "boolean": "#90a0b0",
        "property": "#b08850",
        "tag": "#b64b32",
        "attribute": "#be8f52",
        "error": "#b64b32",
        "warning": "#c8a040",
        "success": "#6a8a58",
        "info": "#7888a0",
        "accent": "#be8f52",
        "cursor": "#d5c9b0",
        "selection": "#be8f5244",
        "ansi_black": "#161210",
        "ansi_red": "#b64b32",
        "ansi_green": "#6a8a58",
        "ansi_yellow": "#c8a040",
        "ansi_blue": "#7888a0",
        "ansi_magenta": "#987088",
        "ansi_cyan": "#5a8888",
        "ansi_white": "#d5c9b0",
    },
    {
        "id": "hokusai",
        "name": "Hokusai",
        "theme_name": "Hokusai — Soft Ecru",
        "subtitle": "Inspired by Katsushika Hokusai's ukiyo-e woodblock prints",
        "appearance": "dark",
        "bg": "#181818",
        "editor_bg": "#1e1e1e",
        "surface": "#272726",
        "elevated": "#323230",
        "text": "#dbd0bf",
        "text_muted": "#a8aaa3",
        "border": "#3a3a38",
        "border_focused": "#344369",
        "comment": "#52524e",
        "keyword": "#5068a0",
        "string": "#edd7a7",
        "function": "#a66a4d",
        "type": "#d9b58e",
        "variable": "#a8aaa3",
        "number": "#d8c090",
        "constant": "#c8b888",
        "operator": "#807869",
        "punctuation": "#a8aaa3",
        "boolean": "#6080b0",
        "property": "#b19774",
        "tag": "#344369",
        "attribute": "#edd7a7",
        "error": "#c05040",
        "warning": "#d0a840",
        "success": "#6a9a68",
        "info": "#5068a0",
        "accent": "#344369",
        "cursor": "#5068a0",
        "selection": "#34436944",
        "ansi_black": "#29272a",
        "ansi_red": "#c05040",
        "ansi_green": "#6a9a68",
        "ansi_yellow": "#d0a840",
        "ansi_blue": "#5068a0",
        "ansi_magenta": "#8868a0",
        "ansi_cyan": "#4898a0",
        "ansi_white": "#dbd0bf",
    },
]


def luminance(hex_color):
    """Calculate relative luminance of a color (0-1)."""
    r, g, b = hex_to_rgb(hex_color)
    return (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255


def for_light_bg(hex_color, max_lum=0.38):
    """Darken a color so it's readable on a light background.

    Preserves hue by scaling RGB proportionally, targeting max_lum luminance.
    """
    r, g, b = hex_to_rgb(hex_color)
    lum = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255
    if lum <= max_lum:
        return hex_color
    factor = (max_lum / max(lum, 0.01)) ** 0.75
    return rgb_to_hex(
        max(0, min(255, r * factor)),
        max(0, min(255, g * factor)),
        max(0, min(255, b * factor)),
    )


def blend_to_white(hex_color, factor=0.80):
    """Blend a color toward white, preserving its hue character.

    factor=0 returns the original color, factor=1 returns pure white.
    """
    r, g, b = hex_to_rgb(hex_color)
    r = r + (255 - r) * factor
    g = g + (255 - g) * factor
    b = b + (255 - b) * factor
    return rgb_to_hex(r, g, b)


def derive_light_artist(dark):
    """Derive a light theme variant from a dark theme definition."""
    # Use the dark theme's text color (the lightest palette color) to derive
    # tinted backgrounds. Each artist gets a distinctly warm/cool/golden bg.
    palette_light = dark["text"]

    # Backgrounds: blend the lightest palette color toward white
    bg = blend_to_white(palette_light, 0.80)
    editor_bg = blend_to_white(palette_light, 0.86)
    surface = blend_to_white(palette_light, 0.74)
    elevated = blend_to_white(palette_light, 0.90)

    # Text: dark, from the palette
    text = for_light_bg(dark["text"], 0.15)
    text_muted = for_light_bg(dark["text_muted"], 0.40)

    # Borders: light gray, tinted
    border = darken(bg, 0.12)
    border_focused = for_light_bg(dark["border_focused"], 0.40)

    # Syntax: darken all dark-theme syntax colors for light bg readability
    comment = for_light_bg(dark["comment"], 0.42)
    keyword = for_light_bg(dark["keyword"], 0.35)
    string = for_light_bg(dark["string"], 0.38)
    function = for_light_bg(dark["function"], 0.32)
    type_ = for_light_bg(dark["type"], 0.38)
    variable = for_light_bg(dark["variable"], 0.35)
    number = for_light_bg(dark["number"], 0.36)
    constant = for_light_bg(dark["constant"], 0.38)
    operator = for_light_bg(dark["operator"], 0.40)
    punctuation = for_light_bg(dark["punctuation"], 0.45)
    boolean = for_light_bg(dark["boolean"], 0.35)
    property_ = for_light_bg(dark["property"], 0.36)
    tag = for_light_bg(dark["tag"], 0.32)
    attribute = for_light_bg(dark["attribute"], 0.38)

    # Status colors: darken slightly for light bg
    error = for_light_bg(dark["error"], 0.40)
    warning = for_light_bg(dark["warning"], 0.40)
    success = for_light_bg(dark["success"], 0.35)
    info = for_light_bg(dark["info"], 0.38)
    accent = for_light_bg(dark["accent"], 0.38)
    cursor = for_light_bg(dark["cursor"], 0.35)

    # ANSI: need darkened versions + swap black/white
    return {
        "id": dark["id"],
        "name": dark["name"],
        "theme_name": dark["theme_name"].replace(" — ", " Light — "),
        "subtitle": dark["subtitle"],
        "appearance": "light",
        "bg": bg,
        "editor_bg": editor_bg,
        "surface": surface,
        "elevated": elevated,
        "text": text,
        "text_muted": text_muted,
        "border": border,
        "border_focused": border_focused,
        "comment": comment,
        "keyword": keyword,
        "string": string,
        "function": function,
        "type": type_,
        "variable": variable,
        "number": number,
        "constant": constant,
        "operator": operator,
        "punctuation": punctuation,
        "boolean": boolean,
        "property": property_,
        "tag": tag,
        "attribute": attribute,
        "error": error,
        "warning": warning,
        "success": success,
        "info": info,
        "accent": accent,
        "cursor": cursor,
        "selection": with_alpha(for_light_bg(dark["accent"], 0.45), 50),
        # ANSI: swap black/white, darken chromatic colors
        "ansi_black": "#2a2520",
        "ansi_red": for_light_bg(dark["ansi_red"], 0.38),
        "ansi_green": for_light_bg(dark["ansi_green"], 0.32),
        "ansi_yellow": for_light_bg(dark["ansi_yellow"], 0.38),
        "ansi_blue": for_light_bg(dark["ansi_blue"], 0.35),
        "ansi_magenta": for_light_bg(dark["ansi_magenta"], 0.35),
        "ansi_cyan": for_light_bg(dark["ansi_cyan"], 0.32),
        "ansi_white": bg,
    }


def build_theme(a):
    """Build a complete Zed theme from artist color definition."""
    is_light = a["appearance"] == "light"

    # For light themes, adjust helper directions
    def subtle_highlight(base, amount):
        return darken(base, amount) if is_light else lighten(base, amount)

    def fade_out(base, amount):
        return lighten(base, amount) if is_light else darken(base, amount)

    return {
        "name": a["theme_name"],
        "appearance": a["appearance"],
        "style": {
            # Backgrounds
            "background": a["bg"],
            "background.appearance": "opaque",
            "editor.background": a["editor_bg"],
            "editor.foreground": a["text"],
            "editor.gutter.background": a["editor_bg"],
            "editor.line_number": a["text_muted"],
            "editor.active_line_number": a["text"],
            "editor.active_line.background": with_alpha(subtle_highlight(a["editor_bg"], 0.04), 80),
            "editor.highlighted_line.background": with_alpha(subtle_highlight(a["editor_bg"], 0.06), 60),
            "editor.invisible": fade_out(a["text_muted"], 0.2) if is_light else darken(a["text_muted"], 0.3),
            "editor.wrap_guide": with_alpha(a["border"], 80),
            "editor.active_wrap_guide": a["border"],
            "editor.indent_guide": with_alpha(a["border"], 60),
            "editor.indent_guide_active": a["border"],
            "editor.subheader.background": a["surface"],
            "editor.document_highlight.read_background": with_alpha(a["accent"], 25 if is_light else 30),
            "editor.document_highlight.write_background": with_alpha(a["accent"], 40 if is_light else 50),
            "editor.document_highlight.bracket_background": with_alpha(a["accent"], 25 if is_light else 30),

            # Surfaces
            "surface.background": a["surface"],
            "elevated_surface.background": a["elevated"],
            "drop_target.background": with_alpha(a["accent"], 30 if is_light else 40),

            # Borders
            "border": a["border"],
            "border.variant": subtle_highlight(a["border"], 0.05),
            "border.focused": a["border_focused"],
            "border.selected": a["border_focused"],
            "border.transparent": "#00000000",
            "border.disabled": fade_out(a["border"], 0.2),

            # Elements
            "element.background": with_alpha(subtle_highlight(a["surface"], 0.03), 80),
            "element.hover": with_alpha(subtle_highlight(a["surface"], 0.06), 100),
            "element.active": with_alpha(a["accent"], 40 if is_light else 60),
            "element.selected": with_alpha(a["accent"], 30 if is_light else 50),
            "element.disabled": with_alpha(a["surface"], 60),

            # Ghost elements
            "ghost_element.background": "#00000000",
            "ghost_element.hover": with_alpha(subtle_highlight(a["surface"], 0.06), 80),
            "ghost_element.active": with_alpha(a["accent"], 35 if is_light else 50),
            "ghost_element.selected": with_alpha(a["accent"], 25 if is_light else 40),
            "ghost_element.disabled": with_alpha(a["surface"], 40),

            # Text
            "text": a["text"],
            "text.muted": a["text_muted"],
            "text.placeholder": fade_out(a["text_muted"], 0.15),
            "text.disabled": fade_out(a["text_muted"], 0.3),
            "text.accent": a["accent"],

            # Icons
            "icon": a["text_muted"],
            "icon.muted": fade_out(a["text_muted"], 0.15),
            "icon.disabled": fade_out(a["text_muted"], 0.3),
            "icon.placeholder": fade_out(a["text_muted"], 0.15),
            "icon.accent": a["accent"],

            # UI components
            "tab_bar.background": a["bg"],
            "tab.inactive_background": a["bg"],
            "tab.active_background": a["editor_bg"],
            "title_bar.background": a["bg"],
            "title_bar.inactive_background": subtle_highlight(a["bg"], 0.02),
            "toolbar.background": a["editor_bg"],
            "status_bar.background": a["bg"],
            "panel.background": a["surface"],
            "panel.focused_border": a["border_focused"],
            "pane.focused_border": a["border_focused"],
            "pane_group.border": a["border"],

            # Scrollbar
            "scrollbar.thumb.background": with_alpha(a["text_muted"], 30 if is_light else 40),
            "scrollbar.thumb.hover_background": with_alpha(a["text_muted"], 55 if is_light else 70),
            "scrollbar.thumb.border": with_alpha(a["border"], 30 if is_light else 40),
            "scrollbar.track.background": "#00000000",
            "scrollbar.track.border": "#00000000",

            # Search
            "search.match_background": with_alpha(a["string"], 40 if is_light else 50),

            # Link
            "link_text.hover": a["keyword"],

            # Status indicators
            "conflict": "#c07040" if is_light else "#d08050",
            "conflict.background": with_alpha("#c07040" if is_light else "#d08050", 15 if is_light else 20),
            "conflict.border": with_alpha("#c07040" if is_light else "#d08050", 30 if is_light else 40),
            "created": a["success"],
            "created.background": with_alpha(a["success"], 15 if is_light else 20),
            "created.border": with_alpha(a["success"], 30 if is_light else 40),
            "deleted": a["error"],
            "deleted.background": with_alpha(a["error"], 15 if is_light else 20),
            "deleted.border": with_alpha(a["error"], 30 if is_light else 40),
            "error": a["error"],
            "error.background": with_alpha(a["error"], 15 if is_light else 20),
            "error.border": with_alpha(a["error"], 30 if is_light else 40),
            "hidden": fade_out(a["text_muted"], 0.3),
            "hidden.background": with_alpha(fade_out(a["text_muted"], 0.3), 15 if is_light else 20),
            "hidden.border": with_alpha(fade_out(a["text_muted"], 0.3), 30 if is_light else 40),
            "hint": fade_out(a["info"], 0.05) if is_light else darken(a["info"], 0.1),
            "hint.background": with_alpha(a["info"], 10 if is_light else 15),
            "hint.border": with_alpha(a["info"], 20 if is_light else 30),
            "ignored": fade_out(a["text_muted"], 0.2),
            "ignored.background": with_alpha(fade_out(a["text_muted"], 0.2), 15 if is_light else 20),
            "ignored.border": with_alpha(fade_out(a["text_muted"], 0.2), 30 if is_light else 40),
            "info": a["info"],
            "info.background": with_alpha(a["info"], 15 if is_light else 20),
            "info.border": with_alpha(a["info"], 30 if is_light else 40),
            "modified": a["warning"],
            "modified.background": with_alpha(a["warning"], 15 if is_light else 20),
            "modified.border": with_alpha(a["warning"], 30 if is_light else 40),
            "predictive": fade_out(a["text_muted"], 0.1),
            "predictive.background": with_alpha(fade_out(a["text_muted"], 0.1), 15 if is_light else 20),
            "predictive.border": with_alpha(fade_out(a["text_muted"], 0.1), 30 if is_light else 40),
            "renamed": a["info"],
            "renamed.background": with_alpha(a["info"], 15 if is_light else 20),
            "renamed.border": with_alpha(a["info"], 30 if is_light else 40),
            "success": a["success"],
            "success.background": with_alpha(a["success"], 15 if is_light else 20),
            "success.border": with_alpha(a["success"], 30 if is_light else 40),
            "unreachable": fade_out(a["text_muted"], 0.3),
            "unreachable.background": with_alpha(fade_out(a["text_muted"], 0.3), 15 if is_light else 20),
            "unreachable.border": with_alpha(fade_out(a["text_muted"], 0.3), 30 if is_light else 40),
            "warning": a["warning"],
            "warning.background": with_alpha(a["warning"], 15 if is_light else 20),
            "warning.border": with_alpha(a["warning"], 30 if is_light else 40),

            # Terminal
            "terminal.background": a["editor_bg"] if is_light else a["bg"],
            "terminal.foreground": a["text"],
            "terminal.bright_foreground": darken(a["text"], 0.1) if is_light else lighten(a["text"], 0.1),
            "terminal.dim_foreground": lighten(a["text"], 0.3) if is_light else darken(a["text"], 0.3),
            "terminal.ansi.black": a["ansi_black"],
            "terminal.ansi.bright_black": darken(a["ansi_black"], 0.15) if is_light else lighten(a["ansi_black"], 0.25),
            "terminal.ansi.dim_black": lighten(a["ansi_black"], 0.15) if is_light else darken(a["ansi_black"], 0.2),
            "terminal.ansi.red": a["ansi_red"],
            "terminal.ansi.bright_red": darken(a["ansi_red"], 0.12) if is_light else lighten(a["ansi_red"], 0.15),
            "terminal.ansi.dim_red": lighten(a["ansi_red"], 0.15) if is_light else darken(a["ansi_red"], 0.25),
            "terminal.ansi.green": a["ansi_green"],
            "terminal.ansi.bright_green": darken(a["ansi_green"], 0.12) if is_light else lighten(a["ansi_green"], 0.15),
            "terminal.ansi.dim_green": lighten(a["ansi_green"], 0.15) if is_light else darken(a["ansi_green"], 0.25),
            "terminal.ansi.yellow": a["ansi_yellow"],
            "terminal.ansi.bright_yellow": darken(a["ansi_yellow"], 0.12) if is_light else lighten(a["ansi_yellow"], 0.15),
            "terminal.ansi.dim_yellow": lighten(a["ansi_yellow"], 0.15) if is_light else darken(a["ansi_yellow"], 0.25),
            "terminal.ansi.blue": a["ansi_blue"],
            "terminal.ansi.bright_blue": darken(a["ansi_blue"], 0.12) if is_light else lighten(a["ansi_blue"], 0.15),
            "terminal.ansi.dim_blue": lighten(a["ansi_blue"], 0.15) if is_light else darken(a["ansi_blue"], 0.25),
            "terminal.ansi.magenta": a["ansi_magenta"],
            "terminal.ansi.bright_magenta": darken(a["ansi_magenta"], 0.12) if is_light else lighten(a["ansi_magenta"], 0.15),
            "terminal.ansi.dim_magenta": lighten(a["ansi_magenta"], 0.15) if is_light else darken(a["ansi_magenta"], 0.25),
            "terminal.ansi.cyan": a["ansi_cyan"],
            "terminal.ansi.bright_cyan": darken(a["ansi_cyan"], 0.12) if is_light else lighten(a["ansi_cyan"], 0.15),
            "terminal.ansi.dim_cyan": lighten(a["ansi_cyan"], 0.15) if is_light else darken(a["ansi_cyan"], 0.25),
            "terminal.ansi.white": a["ansi_white"],
            "terminal.ansi.bright_white": lighten(a["ansi_white"], 0.08) if is_light else lighten(a["ansi_white"], 0.15),
            "terminal.ansi.dim_white": darken(a["ansi_white"], 0.15) if is_light else darken(a["ansi_white"], 0.25),

            # Players (cursor colors)
            "players": [
                {
                    "cursor": a["cursor"],
                    "background": a["cursor"],
                    "selection": a["selection"],
                },
                {
                    "cursor": a["ansi_green"],
                    "background": a["ansi_green"],
                    "selection": with_alpha(a["ansi_green"], 35 if is_light else 50),
                },
                {
                    "cursor": a["ansi_magenta"],
                    "background": a["ansi_magenta"],
                    "selection": with_alpha(a["ansi_magenta"], 35 if is_light else 50),
                },
                {
                    "cursor": a["ansi_cyan"],
                    "background": a["ansi_cyan"],
                    "selection": with_alpha(a["ansi_cyan"], 35 if is_light else 50),
                },
            ],

            # Syntax highlighting
            "syntax": {
                "attribute": {"color": a["attribute"]},
                "boolean": {"color": a["boolean"]},
                "comment": {"color": a["comment"], "font_style": "italic"},
                "comment.doc": {"color": darken(a["comment"], 0.08) if is_light else lighten(a["comment"], 0.1), "font_style": "italic"},
                "constant": {"color": a["constant"]},
                "constructor": {"color": a["type"]},
                "emphasis": {"font_style": "italic"},
                "emphasis.strong": {"font_weight": 700},
                "enum": {"color": a["type"]},
                "function": {"color": a["function"]},
                "function.method": {"color": a["function"]},
                "function.special.definition": {"color": a["function"]},
                "hint": {"color": fade_out(a["text_muted"], 0.05), "font_style": "italic"},
                "keyword": {"color": a["keyword"]},
                "label": {"color": a["property"]},
                "link_text": {"color": a["keyword"], "font_style": "italic"},
                "link_uri": {"color": a["string"]},
                "number": {"color": a["number"]},
                "operator": {"color": a["operator"]},
                "predictive": {"color": fade_out(a["text_muted"], 0.05), "font_style": "italic"},
                "preproc": {"color": a["keyword"]},
                "primary": {"color": a["text"]},
                "property": {"color": a["property"]},
                "punctuation": {"color": a["punctuation"]},
                "punctuation.bracket": {"color": a["punctuation"]},
                "punctuation.delimiter": {"color": a["punctuation"]},
                "punctuation.list_marker": {"color": a["keyword"]},
                "punctuation.special": {"color": a["keyword"]},
                "string": {"color": a["string"]},
                "string.doc": {"color": darken(a["string"], 0.05) if is_light else lighten(a["string"], 0.05), "font_style": "italic"},
                "string.escape": {"color": darken(a["string"], 0.12) if is_light else lighten(a["string"], 0.15)},
                "string.regex": {"color": darken(a["string"], 0.08) if is_light else lighten(a["string"], 0.1)},
                "string.special": {"color": a["string"]},
                "string.special.symbol": {"color": a["constant"]},
                "tag": {"color": a["tag"]},
                "text.literal": {"color": a["string"]},
                "title": {"color": a["keyword"], "font_weight": 700},
                "type": {"color": a["type"]},
                "type.interface": {"color": a["type"], "font_style": "italic"},
                "variable": {"color": a["variable"]},
                "variable.member": {"color": a["property"]},
                "variable.parameter": {"color": darken(a["variable"], 0.05) if is_light else lighten(a["variable"], 0.05)},
                "variable.special": {"color": a["keyword"]},
                "variant": {"color": a["type"]},
            },
        },
    }


def build_family(artist):
    """Build a theme family JSON with both dark and light variants."""
    dark_theme = build_theme(artist)
    light_artist = derive_light_artist(artist)
    light_theme = build_theme(light_artist)
    return {
        "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
        "name": f"Palette Masters: {artist['name']}",
        "author": "Palette Inspiration (paletteinspiration.com)",
        "themes": [dark_theme, light_theme],
    }


def main():
    os.makedirs(THEMES_DIR, exist_ok=True)

    count = 0
    for artist in ARTISTS:
        family = build_family(artist)
        filename = f"palette-masters-{artist['id']}.json"
        filepath = os.path.join(THEMES_DIR, filename)

        with open(filepath, "w") as f:
            json.dump(family, f, indent=2)

        dark_name = family["themes"][0]["name"]
        light_name = family["themes"][1]["name"]
        print(f"Created: {filepath}")
        print(f"  Dark:  {dark_name}")
        print(f"  Light: {light_name}")
        count += 1

    print(f"\nGenerated {count} theme files ({count * 2} themes) in {THEMES_DIR}")
    print("\nTo use a theme in Zed:")
    print("  1. Open Zed")
    print("  2. Press Ctrl+K Ctrl+T (or Cmd+K Cmd+T on macOS)")
    print("  3. Search for 'Palette Masters' or the artist name")


if __name__ == "__main__":
    main()
